first_number = int(input('first number:'))
second_number = int(input('second_number:'))
third_number = int(input('third_number:'))
print('first number is positive:', first_number > 0)
print('first number is negative:', first_number < 0)
print('second number is positive:', second_number > 0)
print('second number is negative:', second_number < 0)
print('third number is positive:', third_number > 0)
print('third number is negative:', third_number < 0)
